apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tfg-ereuse-dpp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ajripa-uoc/TFG-ereuse-dpp'
    targetRevision: main
    path: chart/tfg-ereuse-dpp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tfg-ereuse-dpp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true