
name: Terraform EKS Destroy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Schedule to run at 10pm UTC every day
  #schedule:
  #  - cron: "0 22 * * *" # Run at 10pm UTC every day

env:
  # Terraform verbosity
  TF_LOG: INFO

  # AWS Credentials
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-1

  # Terraform Variables
  TF_VAR_aws_admin_arn: ${{ secrets.AWS_ADMIN_ARN }}
  TF_VAR_github_app_client_id: ${{ secrets.GITHUBAPP_CLIENT_ID }}
  TF_VAR_github_app_secret: ${{ secrets.GITHUBAPP_SECRET }}
  TF_VAR_github_app_id: ${{ secrets.GITHUBAPP_ID }}

jobs:
    destroy:
      name: Terraform destroy
      runs-on: ubuntu-20.04
      defaults:
        run:
          shell: bash
          working-directory: ./terraform/eks

      steps:
        - name: Checkout the repository
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.9.8

        - name: Terraform Init
          id: init
          run: terraform init -upgrade

        - name: Terraform Destroy
          id: destroy
          run: terraform destroy -auto-approve